AWSTemplateFormatVersion: '2010-09-09'
Description: AWS CodeBuild project with GitHub source and webhook

Parameters:
  ProjectName:
    Type: String
    Default: MyGitHubCodeBuildProject
    Description: Name of the CodeBuild project
  GitHubOwner:
    Type: String
    Description: GitHub repository owner (e.g., username or organization)
  GitHubRepo:
    Type: String
    Description: GitHub repository name
  GitHubBranch:
    Type: String
    Default: main
    Description: Branch to trigger builds
  GitHubOAuthTokenSecretArn:
    Type: String
    Description: ARN of the Secrets Manager secret containing the GitHub OAuth token

Resources:
  # IAM Role for CodeBuild
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
              - Effect: Allow 
                Action:
                  - states:StartExecution
                Resource: arn:aws:states:us-west-2:721176634889:stateMachine:TriggerCodebuild

# CodeBuild Project
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref ProjectName
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/${GitHubOwner}/${GitHubRepo}.git
        GitCloneDepth: 1
        Auth:
          Type: OAUTH
          Resource: !Ref GitHubOAuthTokenSecretArn
      SourceVersion: !Ref GitHubBranch
      Artifacts:
        Type: S3
        Location: !Ref ArtifactBucketName
        Name: build-output
        Packaging: ZIP
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        PrivilegedMode: false
      TimeoutInMinutes: 60
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH
            - Type: HEAD_REF
              Pattern: !Sub refs/heads/${GitHubBranch}

Outputs:
  CodeBuildProjectName:
    Description: Name of the CodeBuild project
    Value: !Ref CodeBuildProject